# h2
spring:
    servlet:
        multipart:
            max-file-size: -1
            max-request-size: -1
    datasource:
        url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=true;MODE=PostgreSQL
        username: admin
        password: admin
        driver-class-name: org.h2.Driver
        type: com.zaxxer.hikari.HikariDataSource
        platform: h2
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                temp:
                    use_jdbc_metadata_defaults: true