begin
transaction;

create table if not exists t_job_title (
 	id          bigint not null generated by default as identity,
 	description varchar                     not null,
	created_at  timestamp without time zone not null,
    created_by  bigint                      not null,
    deleted     boolean default false       not null,
    updated_at  timestamp without time zone,
    updated_by  bigint,
    constraint pk_job_title primary key (id)
);

commit;
